
/* @file nt2.js
 * @date 2016.04.28 03:23:04 
 */
(function(a,r){if(a.animate)a.Log("nt2.js loaded");else{var q;q=document.documentElement.style;if(q.webkitTransition!==r||q.MozTransition!==r||q.OTransition!==r||q.msTransition!==r||q.transition!==r){q=document.documentElement.style;var w=(q.webkitTransition!==r?"Webkit":q.MozTransition!==r?"Moz":q.OTransition!==r?"O":q.msTransition!==r?"ms":"")+"Transition";q=function(b,c,d,e){var f=[],g=[],k=[],j=[],l=b.style,d=d||300;a.each(c,function(c,d){g[c]=a.camelize(c);a.isObject(d)?(d.to=d.to||0,f[c]=!a.cssNumber[c]?
parseInt(d.to,10):d.to,k[c]=a.unit(c,d.to),a.isDefined(d.from)&&a.css(b,g[c],parseInt(d.from,10)+k[c])):(f[c]=a.cssNumber[c]?parseInt(d,10):d,k[c]=a.unit(c,d),a.css(b,g[c],f[c]));j.push(c)});setTimeout(function(){l[w]="all "+d+"ms";a.each(j,function(b,c){l[g[c]]=f[c]+k[c]})},15);setTimeout(function(){l[w]="";e&&e.call(b)},d);return b}}else q=function(b,c,d,e){var f=0,g=0,k=0,j=[],l=[],h=[],p=[],q=[],m,d=d||300;a.each(c,function(c,d){h.push(a.camelize(c));a.isObject(d)?(m=d.to,a.isDefined(d.from)?
l.push(!a.cssNumber[c]?parseInt(d.from,10):d.from):l.push(!a.cssNumber[c]?parseInt(a(b).css(c),10):a(b).css(c)),a.css(b,h[g],l[g]+a.unit(c,m))):(m=d,l.push(a(b).css(c)));j.push(a.cssNumber[c]?m:isNaN(parseInt(m,10))?"":parseInt(m,10));p.push(a.unit(c,m));g++;k++});for(c=0;30>c;c++){q[c]=[];for(g=0;g<k;g++)q[c][h[g]]=!a.cssNumber[h[g]]&&!a.isNumeric(parseInt(l[g]))?"":l[g]+(j[g]-l[g])/30*c+("opacity"===h[g]?"":p[g])}for(;30>g;g++)setTimeout(function(){for(g=0;g<k;g++)a.css(b,h[g],q[f][h[g]]);f++},
d/30*g);setTimeout(function(){for(g=0;g<k;g++)a.css(b,h[g],j[g]+p[g]);e&&e.call(b)},d);return b};a.animate=q;a.extend({listenerFunctions:[],listenerMessage:function(b){function c(b){a.each(a.listenerFunctions,function(c,f){f.apply(a,[b.data])})}a.listenerFunctions.push(b);window.addEventListener&&!0!==this.__listenerMessage&&(window.addEventListener("message",c),this.__listenerMessage=!0)},postMessage:function(b,c,a){if(b.postMessage)try{b.postMessage(c,a||"*")}catch(e){}}});a.Window=a.Class.create();
a.Window.prototype={defaultOptions:{dropHeight:30,width:520,height:410,left:100,top:100,minWidth:520,minHeight:410,resize:!1,drag:!1,fixed:!1,zIndex:1E6,rightNode:!0,onChanage:new Function,onClose:new Function,onMinimize:new Function,onMaximize:new Function,onMaxResize:new Function},_tmpMove:null,_tmpStop:null,containter:null,header:null,body:null,chatBody:null,rightElement:null,buttonResize:null,buttonClose:null,buttonMax:null,buttonMin:null,_x:0,_y:0,_isdrag:null,_Style:null,parent:null,initialize:function(b,
c){a.extend(this,this.defaultOptions,b);this.parent=c||null;this.quirks=a.browser.msie6||a.browser.Quirks&&a.browser.oldmsie;this.right=a(window).width()-this.left-this.width;this.bottom=a(window).height()-this.top-this.height;a.Log("$.Window:: left:"+this.left+", top:"+this.top);this._create();this._bind()},close:function(b){this.cancelBubble(b);if(-1>=this.onClose.toString().indexOf("anonymous"))this.onClose();else this.containter.hide(function(){a(this).remove()})},change:function(b){b&&this.onChanage.call(this,
{width:this.width,height:this.height});this._isdrag||(this.chatBody.css({height:this.height-this.dropHeight+"px"}),this.rightNode&&this.rightElement.css("height",this.height-this.dropHeight+"px"))},maxresize:function(){this.onMaxResize()},minimize:function(b,c){!0!==c&&this.cancelBubble(b);this.containter.css({height:"0px",width:"0px"});if(!0!==c)this.onMinimize()},maximize:function(b,c){this.containter.css({height:this.height+"px",width:this.width+"px"});if(!0!==c)this.onMaximize()},cancelBubble:function(b){this.containter.css("z-index",
this.zIndex);a.Event.fixEvent(b).stopPropagation()},changeAttr:function(b,c){this.quirks&&this.clearExpression();a.extend(this,{width:b,height:c,left:Math.max(0,a(window).width()-this.right-b),top:Math.max(0,a(window).height()-this.bottom-c)});this.containter.css({width:this.width+"px",height:this.height+"px",left:this.left+"px",top:this.top+"px"});this.quirks&&this.fixedPosition();this.change(!0)},start:function(b,c){c||this.cancelBubble(b);this._Style=c?{x:"left",y:"top"}:{x:"width",y:"height"};
this.right=a(window).width()-this.left-this.width;this.bottom=a(window).height()-this.top-this.height;this.quirks&&!c&&this.clearExpression();b=a.Event.fixEvent(b);this.containter.css({"z-index":++this.zIndex});this._x=(this._isdrag=c)?b.clientX-this.containter.get(0).offsetLeft||0:this.containter.get(0).offsetLeft||0;this._y=c?b.clientY-this.containter.get(0).offsetTop||0:this.containter.get(0).offsetTop||0;a.browser.msie?this.containter.bind("losecapture",this._tmpStop).get(0).setCapture():(a.Event.fixEvent(b).preventDefault(),
a(window).bind("blur",this._tmpStop));a(document).bind("mousemove",this._tmpMove);a(document).bind("mouseup",this._tmpStop)},move:function(b){window.getSelection?window.getSelection().removeAllRanges():document.selection.empty();var b=a.Event.fixEvent(b),c=b.clientX-this._x,b=b.clientY-this._y,d=a(window).offset();this._isdrag?(this.quirks?(this[this._Style.x]=Math.min(Math.max(c,d.left),d.left+a(window).width()-this.width)-d.left,this[this._Style.y]=Math.min(Math.max(b,d.top),d.top+a(window).height()-
this.height)-d.top):(this[this._Style.x]=Math.min(Math.max(c,0),a(window).width()-this.width),this[this._Style.y]=Math.min(Math.max(b,0),a(window).height()-this.height)),this.containter.css(this._Style.x,(this.quirks?d.left:0)+Math.max(0,this[this._Style.x])+"px"),this.containter.css(this._Style.y,(this.quirks?d.top:0)+Math.max(0,this[this._Style.y])+"px")):(this.quirks?(this[this._Style.x]=Math.min(Math.max(c+(this.quirks?d.left:0),this.minWidth),a(window).width()-this.left),this[this._Style.y]=
Math.min(Math.max(b+(this.quirks?d.top:0),this.minHeight),a(window).height()-this.top)):(this[this._Style.x]=Math.min(Math.max(c,this.minWidth),a(window).width()-this.left),this[this._Style.y]=Math.min(Math.max(b,this.minHeight),a(window).height()-this.top)),this.containter.css(this._Style.x,this[this._Style.x]+"px"),this.containter.css(this._Style.y,this[this._Style.y]+"px"));this.right=a(window).width()-this.left-this.width;this.bottom=a(window).height()-this.top-this.height;this.change(!0)},stop:function(){this.quirks&&
this.fixedPosition();this.containter.css({"z-index":--this.zIndex});a(document).removeEvent("mousemove",this._tmpMove);a(document).removeEvent("mouseup",this._tmpStop);a.browser.msie?this.containter.removeEvent("losecapture",this._tmpStop).get(0).releaseCapture():a(window).removeEvent("blur",this._tmpStop)},fixedPosition:function(){if(this.quirks){var b=a(window).scrollTop();a(window).scrollTop(b+1);this.containter.replaceIEcssText({left:"expression(eval(Math.max((document.documentElement.scrollLeft || document.body.scrollLeft), (document.documentElement.scrollLeft || document.body.scrollLeft) + (document.documentElement.clientWidth  || document.body.clientWidth ) - this.offsetWidth  - "+
this.right+")))",top:"expression(eval(Math.max((document.documentElement.scrollTop  || document.body.scrollTop ), (document.documentElement.scrollTop  || document.body.scrollTop ) + (document.documentElement.clientHeight || document.body.clientHeight) - this.offsetHeight - "+this.bottom+")))"});a(window).scrollTop(b);a(window).scrollLeft(1)}else this.containter.css({left:this.left+"px",top:this.top+"px"})},clearExpression:function(){var b=a(window).offset();this.containter.Expression("left","");this.containter.Expression("top",
"");this.containter.Expression("left","");this.containter.replaceIEcssText({left:b.left+this.left+"px",top:b.top+this.top+"px"})},_for_resize:function(){this.left=Math.max(0,a(window).width()-this.right-this.width);this.top=Math.max(0,a(window).height()-this.bottom-this.height);this.quirks||this.containter.css({left:this.left+"px",top:this.top+"px"})},_create:function(){this.containter=a({className:this.className||"ntalk-window-containter",style:a.STYLE_BODY+"box-sizing:content-box;overflow:hidden;"}).appendTo(this.parent,
!0).css({position:!this.fixed?"absolute":!this.quirks?"fixed":"absolute",border:"none",width:this.width+"px",height:this.height+"px",zIndex:this.zIndex});this.fixedPosition();this.header=a({className:"ntalk-window-head",style:a.STYLE_BODY+"cursor:move;position:relative;left:0;top:0;"}).appendTo(this.containter).css({width:"100%",height:this.dropHeight+"px"});this.buttonClose=a({className:"ntalk-button-close",style:a.STYLE_BODY+"width:20px;height:20px;cursor:pointer;position:static;float:right;position:relative;margin:2px 3px 0 0;line-height:20px;vertical-align:middle;background:none;"}).appendTo(this.header);
this.buttonMax=a({className:"ntalk-button-maxresize",style:a.STYLE_BODY+"width:20px;height:20px;cursor:pointer;position:static;float:right;position:relative;margin:2px 3px 0 0;line-height:20px;vertical-align:middle;background:none;"}).appendTo(this.header);this.buttonMin=a({className:"ntalk-button-min",style:a.STYLE_BODY+"width:20px;height:20px;cursor:pointer;position:static;float:right;position:relative;margin:2px 3px 0 0;line-height:20px;vertical-align:middle;background:none;"}).appendTo(this.header);
this.body=a({className:"ntalk-window-body",style:a.STYLE_BODY+"float:left;width:100%;"}).appendTo(this.containter);this.chatBody=a({className:"ntalk-chat-body",style:a.STYLE_BODY+"width:100%;position:relative;left:0;top:0;"}).appendTo(this.body);this.rightNode&&(this.rightElement=a({className:"ntalk-window-right",style:a.STYLE_BODY+"float:left;display:none;width:100%;"}).appendTo(this.containter));this.resize&&(this.buttonResize=a({className:"window-resize",style:a.STYLE_BODY+"width:10px;height:10px;cursor:nw-resize;position:absolute;right:1px;bottom:1px;font-size:0;background:none;z-index:99;"}).appendTo(this.containter));
a({style:a.STYLE_BODY+"clear:both;"}).appendTo(this.containter);this.change();return this.containter},_bind:function(){var b=this;this.containter.bind("mousedown",function(c){b.drag&&b.start.call(b,c,!0)});this.buttonClose.bind("mousedown",function(c){a.Event.fixEvent(c).stopPropagation();b.close.call(b,c)});this.buttonMax.bind("mousedown",function(c){a.Event.fixEvent(c).stopPropagation();b.maxresize.call(b,c)});this.buttonMin.bind("mousedown",function(c){a.Event.fixEvent(c).stopPropagation();b.minimize.call(b,
c)});this.chatBody.bind("mousedown",function(c){b.cancelBubble.call(b,c)});this.rightNode&&this.rightElement.bind("mousedown",function(c){b.cancelBubble.call(b,c)});this.resize&&this.buttonResize.bind("mousedown",function(c){b.start.call(b,c,!1)});this.fixed&&a(window).bind("resize",function(){b._for_resize()});this._tmpStop=function(c){b.stop.call(b,c)};this._tmpMove=function(c){b.move.call(b,c)}}};a.Queue=a.Class.create();a.Queue.prototype={list:null,length:0,initialize:function(){this.list=[];
this.length=this.list.length},isEmpty:function(){return 0===this.list.length},enQueue:function(b){this.list.push(b);this.length=this.list.length;return this.list[this.length-1]},deQueue:function(){var b;if(this.isEmpty())return null;b=this.list.shift();this.length=this.list.length;return b},queueFront:function(){return this.isEmpty()?null:this.list[0]}};a.pageManage=a.Class.create();a.pageManage.prototype={identid:"",keyid:"",data:null,interID:null,options:null,debug:!1,inter:0.8,count:0,chanageCall:!0,
CON_MANAGE_PAGE_LIST:"IM_EXIST_PAGEARR",pageStore:null,initialize:function(b,c){var d=this,e,f,g=3;this.debug&&a.Log("pageManage.initialize():");this.options=a.extend(this.options,{onChanage:new Function,onInterval:new Function,pageNum:3,timeout:2.5,inter:0.8},b);this.keyid=a.CON_MANAGE_COOKIE+(c?"_"+c.toUpperCase():"");this.identid=this._2shortTime(0,8,13);a.browser.chrome&&(this.options.timeout=5);this.options.timeout*=10;this.options.inter*=1E3;this.inter=this.options.inter;this.pageStore=a.store;
try{for(;g--&&!(e=this.pageStore.get(this.CON_MANAGE_PAGE_LIST)||"",""!=e););f=this._get().m;e=""==e||0==f.length?[]:e.split(",");if(e.length!=f.length&&e.length<=this.options.pageNum){e=[];for(g=0;g<f.length;g++)for(var k in f[g])e.push(k)}e.push(this.identid);this.pageStore.set(this.CON_MANAGE_PAGE_LIST,e.join(","))}catch(j){}var l=a.getTime();this.interID=setInterval(function(){setTimeout(function(){now=a.getTime();d._update(now-l);d.options.onInterval(d.options.timeout,d.data.m);l=a.getTime()},
0)},this.options.inter);a.Event.addEvent(window,"unload",function(){d._remove();setTimeout(function(){},500)})},getIsLastPage:function(){return this.data.m.length},_get:function(){var b=a.cookie.get(this.keyid)||"{}";return a.extend({m:[]},a.JSON.parseJSON(b))},_save:function(){var b=a.JSON.toJSONString(this.data);a.cookie.set(this.keyid,b,0);return b},_remove:function(){var b=this._getIndex();this.data.m.splice(b,1);this._save();if((b=this.pageStore.get(this.CON_MANAGE_PAGE_LIST))&&""!=b){for(var b=
b.split(","),c=0;c<b.length;c++)if(b[c]==this.identid){b.splice(c,1);break}b=b.join(",");""!=b?this.pageStore.set(this.CON_MANAGE_PAGE_LIST,b):this.pageStore.whereClear(this.CON_MANAGE_PAGE_LIST)}},_update:function(b){this.data=this._get();this._clear(b);var b="update",c=this._getIndex();this.data.t=a.formatDate();if(!this.data.m[c])if(this.data.m.length<this.options.pageNum)b="add",this.data.m[c]={};else return;this.data.m[c][this.identid]=this._2shortTime();this._save();this.debug&&a.Log(this.identid+
",pageCount:"+this.data.m.length+","+b+" data:"+a.JSON.toJSONString(this.data.m));if(("add"==b||!0!==this.chanageCall)&&this.count!=this.data.m.length)this.options.onChanage.call(this,this.data.m.length,this.data.m),this.count=this.data.m.length;this.chanageCall=!1},_clear:function(b){var c=this._2shortTime();if(this.data.m.length)for(var a=0,e;a<this.data.m.length;a++)if(this.data.m[a])for(var f in this.data.m[a])if("function"!=typeof this.data.m[a][f]&&(e=c-this.data.m[a][f],Math.abs(e)>this.options.timeout+
b/100)){this.data.m.splice(a,1);this.chanageCall=!0;e=this.pageStore.get(this.CON_MANAGE_PAGE_LIST);if(!e||""==e)return;e=e.split(",");for(var g=0;g<e.length;g++)if(e[g]==f){e.splice(g,1);break}e=e.join(",");""!=e?this.pageStore.set(this.CON_MANAGE_PAGE_LIST,e):this.pageStore.whereClear(this.CON_MANAGE_PAGE_LIST)}},_getIndex:function(){if(!this.data.m.length)return 0;for(var b=0;b<this.data.m.length;b++)if(this.data.m[b])for(var c in this.data.m[b])if(this.data.m[b]&&!a.isFunction(this.data.m[b][c])&&
c===this.identid)return b;return b},_2shortTime:function(b,c,d){b=(b?b:a.getTime()).toString();return b.substring(c||5,d||11)}};q=a;var h={disabled:!1},s=a.browser.msie,p;h.toJSONString=function(b){return null==b?"":a.JSON.toJSONString(b)};h.parseJSON=function(b){if("object"==typeof b)return b||r;try{return a.JSON.parseJSON(b)}catch(c){return b||r}};if(function(){var b=null;try{b=window.localStorage}catch(c){return a.Log("localStorage:"+c.message,3),!1}if(b)try{return null!==localStorage.getItem("test")&&
localStorage.removeItem("test"),localStorage.setItem("test","test"),"test"==localStorage.getItem("test")?(localStorage.removeItem("test"),!0):!1}catch(d){return a.Log("The browser localStorage is unavailable. "+d.message,3),!1}}())p=window.localStorage,h.set=function(b,c){if(!c||c===r||null===c)return h.remove(b);try{"function"==typeof p.setItem?p.setItem(b,h.toJSONString(c)):p[b]=h.toJSONString(c)}catch(d){if("QUOTA_EXCEEDED_ERR"==d.name.toUpperCase()){h.remove(b);try{p.setItem(b,h.toJSONString(c))}catch(e){a.Log("store.set:"+
e.message,3)}}}return c},h.get=function(b){return h.parseJSON(p.getItem(b))},h.remove=function(b){try{p.removeItem(b)}catch(c){a.Log("store.remove:"+c.message,3)}},h.clear=function(){try{p.clear()}catch(b){a.Log("store.clear:"+b.message,3)}},h.getAll=function(){for(var b={},c=0;c<p.length;++c){var a=p.key(c);b[a]=h.get(a)}return b};else if(s){var v=RegExp("[!\"#$%&'()*+,/\\\\:;<=>?@[\\]^`{|}~]","g"),t,u,s=function(b){return function(){var c;c=Array.prototype.slice.call(arguments,0);c.unshift(p);try{t.appendChild(p)}catch(a){t.insertBefore(p,
t.firstChild)}p.addBehavior&&p.addBehavior("#default#userData");for(var e=20;0<e;){e--;try{p.load("nTK-LS");break}catch(f){}}c=b.apply(h,c);t.removeChild(p);return c}};try{u=new ActiveXObject("htmlfile"),u.open(),u.write('<script type="text/javascript">document.w=window;<\/script><iframe src="/favicon.ico"></iframe>'),u.close(),t=u.w.frames[0].document,p=t.createElement("div")}catch(x){p=document.createElement("div"),t=document.body||document.getElementsByTagName("head")[0]||document.documentElement}h.set=
s(function(b,c,a){c=c.replace(v,"___");if(!a||a===r||null===a)return h.remove(c);b.setAttribute(c,h.toJSONString(a));try{b.save("nTK-LS")}catch(e){}return a});h.get=s(function(b,a){a=a.replace(v,"___");return h.parseJSON(b.getAttribute(a))});h.remove=s(function(b,a){a=a.replace(v,"___");b.removeAttribute(a);b.save("nTK-LS")});h.clear=s(function(b){try{var a=b.XMLDocument.documentElement.attributes}catch(d){return}b.load("nTK-LS");for(var e=0,f=a.length;e<f;e++)b.removeAttribute(a[e].name);b.save("nTK-LS")});
h.getAll=s(function(b){try{var a=b.XMLDocument.documentElement.attributes}catch(d){return}for(var e={},f=0,g=a.length;f<g;++f){var k=a[f],j=k.name.replace(v,"___");e[k.name]=h.parseJSON(b.getAttribute(j))}return e})}else h.set=function(){a.Log("The browser localStorage is unavailable.",3)},h.get=new Function,h.remove=new Function,h.clear=new Function,h.getAll=new Function;try{h.set("__cometd__","__cometd__"),"__cometd__"!=h.get("__cometd__")&&(h.disabled=!0),h.remove("__cometd__")}catch(y){h.disabled=
!0}h.whereClear=function(b){var c=this,d=this.getAll();a.each(d,function(a){-1<a.indexOf(b)&&c.remove(a)})};h.enabled=!h.disabled;q.store=h;a.comet=a.Class.create();a.comet.prototype={name:"public.comet",version:"2014.05.17",connType:"login",options:null,fix:"",id:"",count:0,sendIntervalID:null,_ipExpr:/^https?:\/\/\d+\.\d+\.\d+\.\d+(:\d+)?\/(.*?)$/gi,_cacheElement:{},_connectTimeID:{},defaultOption:{muDomain:3,timeout:20,onCallback:new Function,onComplete:new Function,onAbnormal:new Function,onTimeout:new Function},
initialize:function(b,c){var d=this;this.uri=b;this.fix=a.randomChar();this.uri||a.Log("comet uri is null",3);this.callMethod=window;this.callbackName="callback_"+this.fix;this.callMethod[this.callbackName]=function(){d._connectCallback.call(d,d.id,arguments)};this.options=a.extend({},this.defaultOption,c);this.initConnectionPooling()},initMessageQueue:function(){this.messageQueue||(this.messageQueue=new a.Queue,this.messageQueue.addMessage=function(b){for(var a=0;a<this.length;a++)if(this.list[a].msgid==
b.msgid&&this.list[a].index==b.index)return!1;this.enQueue(b);return!0},this.messageQueue.nextMessage=function(b,a){if(this.isEmpty())return null;if(!b)return this.queueFront();for(var d=0;d<this.length;d++)if(this.list[d].msgid==b&&this.list[d].body.sendpacket==a)return this.list[d+1]},this.messageQueue.removeMessage=function(){for(var b=0;b<this.length;b++);this.list.splice(b,1);this.length=this.list.length})},initConnectionPooling:function(){if(!this.connectionPooling){this._ipExpr.test(this.uri)&&
(this.options.muDomain=1);this.connectionPooling=new a.Queue;this.connectionPooling.get=function(){for(var b,a,e=0;e<this.list.length;e++){if(!1===this.list[e].lock&&(!b||b.rTimesample>this.list[e].rTimesample))b=this.list[e];if(!a||this.list[e].sTimesample<a.sTimesample)a=this.list[e]}b=b||a;this.recover(b.uri,!0);return b};this.connectionPooling.getConnect=function(){var b=this.get();return{uri:b.uri,url:b.uri+(/\?$/ig.test(b.uri)?"&":"?")}};this.connectionPooling.recover=function(b,d,e,f){for(var g=
0;g<this.list.length;g++)if(this.list[g].uri==b)return(this.list[g].lock=d)?(this.list[g].sTimesample=e||a.getTime(),this.list[g].rTimesample=0):this.list[g].rTimesample=f||a.getTime(),!0;return!1};for(var b=0;b<=this.options.muDomain;b++)this.connectionPooling.enQueue({uri:0===b?this.uri.toString().replace(/(https?:\/\/)(.*?)(\-\d+)?\./ig,"$1$2."):this.uri.toString().replace(/(https?:\/\/)(.*?)(\-\d+)?\./ig,"$1$2-"+(+b-1)+"."),lock:!1,sTimesample:0,rTimesample:0})}},connect:function(b,c){var d,e,
f=this.count++;this.connType="login";this.id=this.fix+"_"+f;b[c||"callbackname"]=this.callbackName;this.connectOptions=a.extend(b,{ts:a.getTime()});d=this.connectionPooling.getConnect();e=d.url+a.toURI(this.connectOptions);this._cacheElement[this.id]=this._createConnect(e,this.id,f,d)},kalive:function(b,c){var d,e,f=this.count++;this.connType="kalive";this.id=this.fix+"_"+f;b[c||"callbackname"]=this.callbackName;this.kaliveOptions=a.extend(this.kaliveOptions,b,{ts:a.getTime()});d=this.connectionPooling.getConnect();
e=d.url+a.toURI(this.kaliveOptions);this._cacheElement[this.id]=this._createConnect(e,this.id,f,d)},disconnectServer:function(b,c){return this.flashGoServer=this.connectionPooling.getConnect().url+a.toURI(!1===c?b:a.extend(b,{ts:a.getTime()}))},disconnect:function(){a.require(this.flashGoServer,function(b){a(b.error?b.target:b).remove()});window[this.callbackName]=new Function},reconnect:function(){this.connect(this.connectOptions)},send:function(b,c){var d=this,e=this.connectionPooling.getConnect(),
f=this.mdyServerAddr(e.url)+a.toURI(b);a.require(f+"#rnd",function(b){d.connectionPooling.recover(e.uri,!1);c&&c.call(d,b.error);a(b.error?b.target:b).remove()});return!0},mdyServerAddr:function(b){return b.replace(/\/flashgo/i,"/httpgo")},post:function(b,c){var d=this,e=this.connectionPooling.getConnect();new a.POST(this.mdyServerAddr(e.url),b,function(){d.connectionPooling.recover(e.uri,!1);c&&c.call(d,!0)})},_createConnect:function(b,c,d,e){var f=this,g,d=document.head||nTalk("head")[0]||document.documentElement;
g=a({className:c,tag:"script",type:"text/javascript",async:"async",src:b,charset:"utf-8"}).appendTo(d);b=g.get(0).readyState?"onreadystatechange":"onload";g.get(0)[b]=g.get(0).onerror=function(b){var d=g.get(0).readyState,b=a.Event.fixEvent(b);/^(loaded|complete|undefined)$/.test(d)&&(f.connectionPooling.recover(e.uri,!1),"error"!==b.type?setTimeout(function(){f._connectComplete(b,c);g.remove()},a.browser.msie?800:50):(f._connectAbnormal(b,c),g.remove()))};this._connectTimeID[c]=setTimeout(function(){g.first().remove();
f._connectTimeout("timeout",c)},1E3*+this.options.timeout+1E4);return g.get(0)},_connectCallback:function(b,c){c=Array.prototype.slice.call(c);a("."+b).remove();this._cacheElement[b]?(this._stopCallComplete(b,"callback"),this.options.onCallback.apply(self,[!0,c])):this.options.onCallback.apply(self,[!1,c])},_connectComplete:function(b,a){var d=Array.prototype.slice.call(arguments);this._cacheElement[a]&&(this._stopCallComplete(a,"complete"),this.options.onComplete.apply(self,[this.connType].concat(d)))},
_connectAbnormal:function(b,a){var d=Array.prototype.slice.call(arguments);this._cacheElement[a]&&(this._stopCallComplete(a,"abnormal"),this.options.onAbnormal.apply(self,[this.connType].concat(d)))},_connectTimeout:function(b,a){var d=Array.prototype.slice.call(arguments);this._cacheElement[a]&&(this._stopCallComplete(a,"timeout"),this.options.onTimeout.apply(self,[this.connType].concat(d)))},_stopCallComplete:function(b){var c=this._cacheElement[b];c?c.onload=c.onreadystatechange=c.onerror=new Function:
a.Log("stop error id:"+b,3);delete this._cacheElement[b];clearTimeout(this._connectTimeID[b]);delete this._connectTimeID[b]},_createScriptPCID:function(b){return"guest"+[b?"TEMP"+a.randomChar(4):a.randomChar(8),a.randomChar(4),a.randomChar(4),a.randomChar(4),a.randomChar(12)].join("-")}};a.mqttws=a.Class.create();a.mqttws.prototype={name:"public.mqttws",version:"2015.04.10",connect:null,subscriptions:[],messages:[],connected:!1,recCount:0,waitTime:500,_wsKeepaliveId:null,_options:{url:null,siteid:null,
pcid:null,onCallback:null,loginMsg:null,timeout:3,keepAliveInterval:90},initialize:function(b){var c=this;this.options=a.extend({},c._options,b);this.options.pcid=(this.options.siteid+"_"+this.options.pcid.substring(5)).substring(0,23);a.require({mqtt:"mosquitto.js?siteid="+a.extParmas.siteid},function(){c.connect=new a.Mosquitto;c.connect.onmessage=function(b,e){var f=a.JSON.parseJSON(e);c.options.onCallback.apply(this,[!0,[f.method].concat(f.params)])};c.connect.ondisconnect=function(){null!=this._wsKeepaliveId&&
(clearInterval(this._wsKeepaliveId),this._wsKeepaliveId=null)};c.connect.onconnect=function(b){0==b?(c.connect.subscribe("foo",0),c.connect.publish("foo",c.options.loginMsg,0,0)):c.reconnect()};c.connect.onreconnect=function(){c.reconnect()};c.connect.connect(c.options.url,c.options.keepAliveInterval,c.options.pcid)})},reconnect:function(){var b=this;this._waitTime=3>++this.recCount?500:1E3*+"034567890".charAt(Math.ceil(5*Math.random()));setTimeout(function(){b.connect.connect(b.options.url,b.options.keepAliveInterval,
b.options.pcid)},this._waitTime)},disconnect:function(){this.connect.closeFlag=!0;this.connect.disconnect()},kalive:function(b){var a=this;this._wsKeepaliveId||(this._wsKeepaliveId=setInterval(function(){a.connect.publish("foo",b,0,!1)},1E3*this.options.keepAliveInterval))}};a.extend({htmlToElement:function(b){var c,d;if(a.browser.msie)try{c=new ActiveXObject("MSXml.DOMDocument"),c.loadXML(b),d=c.childNodes}catch(e){c=document.createElement("DIV"),c.innerHTML=b,d=c.childNodes}else c=document.createElement("DIV"),
c.innerHTML=b,d=c.childNodes;return d},elementToObject:function(b){var c={},d;d=a.isArray(b)||b.talkVersion?b[0]:b;c[d.tagName.toLowerCase()]=d.innerHTML;if(d.attributes)for(var e=0;e<d.attributes.length;e++){if(b=d.attributes[e].name)c[b]=d.attributes[e].value}else c.msg=d.textContent;return c},jsonToxml:function(b){var c=this,d="",e;if("object"==typeof b)a.each(b,function(f,g){if("string"==typeof g&&"text"==f)d=g;else if(a.isArray(b))d+=c.jsonToxml(g);else{d+="<"+f;if("object"==typeof g.attributes){for(var k in g.attributes)g.attributes.hasOwnProperty(k)&&
(d+=" "+k+'="'+g.attributes[k]+'"');delete g.attributes}e=c.jsonToxml(g);d=g&&e?d+(">"+e+"</"+f+">"):d+("></"+f+">")}});else return b;return d},utils:{options:{},handleLinks:function(b,c){this.options=a.extend({},this.options,c);for(var b=b||"",d=0;d<this.linkPatterns.length;d++)b=b.replace(this.linkPatterns[d][0],this.linkPatterns[d][1]);return b},linkPatterns:[[/\[link\s+reconnect=([^\s\[\]'"]+)\s*[^\[\]]*]([^\[\]]+)\[\/\s*link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get(\'$1\').reconnect(this);return false;" >$2</a>'],
[/\[link\s+message=([^\s\[\]'"]+)\s*[^\[\]]\s*source=([^\s\[\]'"]+)\s*[^\[\]]*]([^\[\]]+)\[\/\s*link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get(\'$1\').switchUI(\'message\', $2);return false;" >$3</a>'],[/\[link\s+cancel=([^\s\[\]'"]+)\s+action=([^\s\[\]'"]+)\s*[^\[\]]*]([^\[\]]+)\[\/\s*link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get(\'$1\').cancelUpload(\'$2\');return false;" >$3</a>'],
[/\[link\s+resend=([^\s\[\]'"]+)\s+msgid=([^\s\[\]'"]+)\s*[^\[\]]*]([^\[\]]+)\[\/\s*link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get(\'$1\').resend(\'$2\', this);return false;" >$3</a>'],[/\[link\s*manual=([^\s\[\]'"]+)](.*?)\[\/link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get(\'$1\').switchServerType(true);return false;" >$2</a>'],
[/\[link\s*artificial=([^\s\[\]'"]+)](.*?)\[\/link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get(\'$1\').switchServerType(true);return false;" >$2</a>'],[/\[link\s*robot](.*?)\[\/link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get().switchServerType(false, 2);return false;" >$1</a>'],[/\[link\s*robotindex=([^\s\[\]'"]+)](.*?)\[\/link]/gi,
'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;" href="javascript:void(0);" onclick="nTalk.chatManage.get(\'{$settingid}\').send(\'$1\');return false;">$2</a>'],[/\[link\s*href=(.*?)](.*?)\[\/link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;cursor:pointer;" href="$1">$2</a>'],[/\[link\s*(.*?)?](.*?)\[\/link]/gi,'<a style="'+a.STYLE_BODY+'display:inline-block;color:#005ffb;text-decoration:none;cursor:pointer;" href="javascript:void(0);"'+
(a.browser.iOS?' href="$1" target="_blank"':" onclick=\"window.open('$1')\"")+">$2</a>"],[/\{\$(\w+)}/gi,function(b,c){return a.utils.options[c]||""}]]},toHSL:function(b){return a.isHex(b)?a.rgb2HSL(a.hex2RGB(b)):a.isRGB(b)?a.rgb2HSL(b):b},isHex:function(b){return"string"==typeof b&&/^#?([0-9a-f]{3}|[0-9a-f]{6})$/ig.test(b)},isRGB:function(b){return a.isObject(b)&&a.isDefined(b.r)&&a.isDefined(b.g)&&a.isDefined(b.b)},isHSL:function(b){return a.isObject(b)&&a.isDefined(b.h)&&a.isDefined(b.s)&&a.isDefined(b.l)},
hex2RGB:function(b){var b=b.toString().replace("#",""),a=b.split(""),d={};return d=3==b.length?{r:parseInt(a[0]+a[0],16),g:parseInt(a[1]+a[1],16),b:parseInt(a[2]+a[2],16)}:6==b.length?{r:parseInt(a[0]+a[1],16),g:parseInt(a[2]+a[3],16),b:parseInt(a[4]+a[5],16)}:{r:0,g:0,b:0}},rgb2HSL:function(b){var a,d,e,f,g,k,j={};a=b.r/255;d=b.g/255;b=b.b/255;e=Math.min(a,d,b);k=Math.max(a,d,b);g=k-e;j.l=(k+e)/2;0==g?(j.h=0,j.s=0):(j.s=0.5>j.l?g/(k+e):g/(2-k-e),e=((k-a)/6+g/2)/g,f=((k-d)/6+g/2)/g,g=((k-b)/6+g/2)/
g,a==k?j.h=g-f:d==k?j.h=1/3-g+e:b==k&&(j.h=2/3-e+f),0>j.h&&(j.h+=1),1<j.h&&(j.h-=1));return j}});a.fn.extend({animate:function(b,c,d){return a.each(this,function(e,f){a.animate(f,b,c,d)})},show:function(b,c){a.isFunction(b)&&(c=b,b=500);return this.animate({visibility:"visible",opacity:{from:0,to:1}},b||500,c)},hide:function(b,c){a.isFunction(b)&&(c=b,b=500);return this.animate({opacity:{to:0}},b||500,c)},gradient:function(b,c,d){var e,f;return b?a.each(this,function(g,k){a.browser.oldmsie&&(e=/top|bottom/.test(b)?
0:1,/right|bottom/.test(b)&&(f=c,c=d,d=f));if(a.browser.webkit){switch(b){case "top":e="0% 100%,0% 0%";break;case "right":e="0% 0%,100% 0%";break;case "bottom":e="0% 0%,0% 100%";break;case "left":e="100% 0%,0% 0%"}a(k).css("background-image",!b?"none":"-webkit-gradient(linear,"+e+",color-stop(1, "+c+"),color-stop(0, "+d+"))")}else a.browser.gecko?a(k).css("background-image",!b?"none":"-moz-linear-gradient("+b+", "+c+", "+d+")"):a.browser.oldmsie?k.style.filter=k.currentStyle.filter.replace(/progid:DXImageTransform\.Microsoft\.gradient\((.*?)\)\s*/gi,
"")+(!b?"":" progid:DXImageTransform.Microsoft.gradient(GradientType="+e+",startColorstr='"+c+"', endColorstr='"+d+"')"):a.browser.msie?a(k).css("background-image",!b?"none":"-ms-linear-gradient("+b+", "+c+", "+d+")"):a(k).css("background-image",!b?"none":"linear-gradient("+b+", "+c+", "+d+")")}):a.each(this,function(b,c){a.browser.oldmsie?a(c).css("filter","none"):a(c).css("background-image","none")})}});a.extend({base64:{_strKey:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=",
encode:function(b){for(var c=a.base64,d="",e,f,g,k,j,l,h=0,b=c._utf8_encode(b||"");h<b.length;)e=b.charCodeAt(h++),f=b.charCodeAt(h++),g=b.charCodeAt(h++),k=e>>2,e=(e&3)<<4|f>>4,j=(f&15)<<2|g>>6,l=g&63,isNaN(f)?j=l=64:isNaN(g)&&(l=64),d=d+c._strKey.charAt(k)+c._strKey.charAt(e)+c._strKey.charAt(j)+c._strKey.charAt(l);return d},decode:function(b){for(var c=a.base64,d="",e,f,g,k,j,l=0,b=(b||"").replace(/[^A-Za-z0-9\+\/=]/g,"");l<b.length;)e=c._strKey.indexOf(b.charAt(l++)),f=c._strKey.indexOf(b.charAt(l++)),
k=c._strKey.indexOf(b.charAt(l++)),j=c._strKey.indexOf(b.charAt(l++)),e=e<<2|f>>4,f=(f&15)<<4|k>>2,g=(k&3)<<6|j,d+=String.fromCharCode(e),64!=k&&(d+=String.fromCharCode(f)),64!=j&&(d+=String.fromCharCode(g));return d=c._utf8_decode(d)},_utf8_encode:function(b){for(var b=b.replace(/\r\n/g,"\n"),a="",d=0;d<b.length;d++){var e=b.charCodeAt(d);128>e?a+=String.fromCharCode(e):(127<e&&2048>e?a+=String.fromCharCode(e>>6|192):(a+=String.fromCharCode(e>>12|224),a+=String.fromCharCode(e>>6&63|128)),a+=String.fromCharCode(e&
63|128))}return a},_utf8_decode:function(b){for(var a="",d=0,e,f,g;d<b.length;)e=b.charCodeAt(d),128>e?(a+=String.fromCharCode(e),d++):191<e&&224>e?(f=b.charCodeAt(d+1),a+=String.fromCharCode((e&31)<<6|f&63),d+=2):(f=b.charCodeAt(d+1),g=b.charCodeAt(d+2),a+=String.fromCharCode((e&15)<<12|(f&63)<<6|g&63),d+=3);return a}},FORM:{createInput:function(b,c,d){for(var e=[],f,g,k=a.browser.mobile,c=a.extend({id:"",rowspan:0,style:""},c),j='<span class="ntkf-text-red" style="'+a.STYLE_BODY+'padding:2px 5px 2px 0;color:#f00;">'+
(d||"")+"</span>",l=0;l<b.length;l++){d=a.extend({titlewidth:"80px",inputwidth:"auto",input:{width:"90%",height:"auto"}},b[l]);f=k?d.title:d.title+(d.title.length==a.enLength(d.title)?":":"\uff1a");/zh_cn|zh_tw/.test(a.lang.language)&&16<a.enLength(d.title)||d.multipart||/radio|checkbox/.test(d.type)&&2<d.options.length?(d.multipart=!0,e.push(k?'<tr style="'+a.STYLE_BODY+'"><td style="'+a.STYLE_BODY+'width:100%;"><div style="'+a.STYLE_BODY+'width:100%; line-height:14px; font-size:14px; font-weight:bold; text-align:center; color:#333333; margin: 15px 0px 20px 0px">'+
f+"</div>":['<tr style="',a.STYLE_BODY,'"><td style="',a.STYLE_BODY,'vertical-align:top;line-height:28px;color:#333;" colspan="2"><div style="',a.STYLE_BODY,'margin:5px 10px 5px 10px;color:#5a5a5a;">',f,!0===d.required?j:"","</div></td></tr>",'<tr style="'+a.STYLE_BODY+'"><td style="',a.STYLE_BODY,'padding:0 5px 0 0;text-align:right;vertical-align:top;line-height:28px;color:#333;"></td>','<td style="'+a.STYLE_BODY+"line-height:28px;width:"+d.inputwidth+';">'].join(""))):e.push('<tr style="'+a.STYLE_BODY+
'">'+(k?"":'<td style="'+a.STYLE_BODY+"padding:0 5px 0 0;text-align:right;vertical-align:top;line-height:28px;color:#333;width:"+d.titlewidth+';"><div style="'+a.STYLE_BODY+'margin:4px 0 0 0;text-align:right;color:#5a5a5a;">'+(!0===d.required?j:"")+f+"</div></td>")+'<td style="'+a.STYLE_BODY+"line-height:28px;width:"+(k?"100%":d.inputwidth)+';">');switch(d.type){case "select":e.push('<select data-index="'+l+'" name="'+d.name+'" style="'+a.STYLE_BODY+"border:1px solid #ccc;height:24px;color:#333;margin:0 0 4px;line-height:20px;width:"+
(k?"99%":d.input.width)+';">');e.push('<option value="" style="'+a.STYLE_BODY+'color:#ccc;">'+d.defaultText+"</option>");for(g=0;g<d.options.length;g++)f=d.options[g],f="string"==typeof f?{text:f,value:f}:f,e.push('<option value="'+f.value+'" style="'+a.STYLE_BODY+'color:#333;">'+f.text+"</option>");e.push("</select>");break;case "radio":e.push('<ul style="'+a.STYLE_BODY+'list-style:none;">');for(var h=0,p;h<d.options.length;h++)f=d.options[h],f="string"==typeof f?{text:f,value:f}:f,p=d.name+"_"+
h,g=d.defaultText==f.value?" checked":"",e.push('<li class="form-item" style="'+a.STYLE_BODY+'list-style:none;padding:0 2px 0 0;color:#000;float:left;"><input type="radio" name="'+d.name+'"id="'+p+'" value="'+f.value+'" _custom_text="'+f.text+'" style="'+a.STYLE_BODY+'color:#333;display:inline-block"'+g+' /><label for="'+p+'" style="'+a.STYLE_BODY+'display:inline;color:#000;">'+f.text+"</label></li>");e.push('<li style="'+a.STYLE_BODY+'list-style:none;clear:both;width:0;height:0;"></li>');e.push("</ul>");
break;case "checkbox":e.push('<ul style="'+a.STYLE_BODY+'list-style:none;">');for(h=0;h<d.options.length;h++)f=d.options[h],f="string"==typeof f?{text:f,value:f}:f,p=d.name+"_"+h,g=d.defaultText==f.value?" checked":"",e.push('<li class="form-item" style="'+a.STYLE_BODY+'list-style:none;padding:0 2px 0 0;float:left;"><input type="checkbox" name="'+d.name+'" id="'+p+'" value="'+f.value+'" _custom_text="'+f.text+'" style="'+a.STYLE_BODY+'color:#333;"'+g+' /><label for="'+p+'" style="'+a.STYLE_BODY+'display:inline;color:#000;">'+
f.text+"</label></li>");e.push('<li style="'+a.STYLE_BODY+'list-style:none;clear:both;width:0;height:0;"></li>');e.push("</ul>");break;case "textarea":e.push('<textarea data-index="'+l+'" name="'+d.name+'" style="'+a.STYLE_BODY+"border:1px solid #ccc;color:#ccc;width:"+(k?"99%":d.input.width)+";height:"+d.input.height+';"'+(a.browser.html5?' placeholder="'+d.defaultText+'">':">"+d.defaultText)+"</textarea>");break;default:e.push('<input data-index="'+l+'" type="text" name="'+d.name+'"'+(a.browser.html5?
' placeholder="'+d.defaultText+'" value=""':' value="'+d.defaultText+'"')+' maxlength="32" style="'+a.STYLE_BODY+"border:1px solid #ccc;height:24px;width:"+(k?"99%":d.input.width)+';margin:0 0 4px;color:#ccc;"'),"phone"==d.verification&&e.push(" onblur=\"this.value=this.value.replace(/[^0-9-]+/, '');\" onkeyup=\"var keyCode=(event || window.event).keyCode; if( !/16|17|35|36|37|38|39|40/i.test(keyCode) ){this.value=this.value.replace(/[^0-9-]+/, '');}\""),e.push(" />")}d.messageid&&(e.push('<div style="'+
a.STYLE_BODY+'display:none;color:#EF7208;" class="form-info '+d.messageid+'">'),e.push('<div style="'+a.STYLE_BODY+"margin:2px;width:15px;height:15px;float:left;background:transparent url("+a.sourceURI+'/images/chaticon.png) no-repeat -160px -39px;"></div>'),e.push('<div style="'+a.STYLE_BODY+'color:#EF7208;float:left;" class="chat-view-info"></div>'),e.push('<div style="'+a.STYLE_BODY+'clear:both;width:0;height:0;"></div>'),e.push("</div>"));e.push("</td>");c.style&&0===l&&e.push('<td style="'+a.STYLE_BODY+
c.style+'" id="'+c.id+'" rowspan="'+c.rowspan+'"></td></tr>')}return e.join("")},bindFormEvent:function(b,c){a(c).find("input[type=text], textarea").bind("focus",function(){var c=a(this).css({color:"#333","border-color":a.browser.mobile?"#0079fe":"#666"}),e=c.attr("data-index")||0;b[e].defaultText==c.val()&&c.val("")}).bind("blur",function(){var c=a(this).css("border-color","#ccc"),e=c.attr("data-index")||0,e=b[e].defaultText;""===c.val()&&c.val(e);(""===c.val()||c.val()==e)&&c.css("color","#ccc")})},
verificationForm:function(b,c,d,e){for(var f,g,k=[],j,l,h=!1,p=/\d{6,}/i,q=/^[a-zA-Z0-9\._-]+@[a-zA-Z0-9_-]+(\.[a-zA-Z0-9_-]+)+$/i,m=0;m<b.length;m++){switch(b[m].type){case "checkbox":l=[];f=a(d).find("input[name="+b[m].name+"]");g=a(d).find("input[name="+b[m].name+"][checked]");for(j=0;j<g.length;j++)l.push({value:g.get(j).value,text:a(g.get(j)).attr("_custom_text")});break;case "radio":l={value:"",text:""};f=a(d).find("input[name="+b[m].name+"]");a(d).find("input[name="+b[m].name+"][checked]").each(function(b,
c){c.checked&&(l={value:a(c).val()||"",text:a(c).attr("_custom_text")})});break;case "select":f=a(d).find("select[name="+b[m].name+"]");l=a("option[selected]",f).val()||"";l=b[m].defaultText&&l==b[m].defaultText?"":l;break;case "textarea":f=a(d).find("textarea[name="+b[m].name+"]");b[m].defaultText&&b[m].defaultText==f.val()?(l="",f.val("")):l=f.val().replace(/(^\s*)|(\s*$)/g,"");break;default:f=a(d).find("input[name="+b[m].name+"]"),b[m].defaultText&&b[m].defaultText==f.val()?(l="",f.val("")):l=
f.val().replace(/(^\s*)|(\s*$)/g,"")}g="string"==typeof l?""===l||!l.length:a.isArray(l)?0===l.length:""===l.value;j=b[m].messageid&&b[m].message?!0:!1;var r=a(d).find("."+b[m].messageid),s=a(d).find("."+b[m].messageid+" .chat-view-info");b[m].required&&g?(this.showError(j,b[m].message[0],s,r,f),h=!0):"phone"==b[m].verification&&!g&&!p.test(l)?(this.showError(j,b[m].message[1],s,r,f),h=!0):"email"==b[m].verification&&!g&&!q.test(l)?(this.showError(j,b[m].message[1],s,r,f),h=!0):b[m].min&&!g&&a.enLength(l)<
b[m].min?(this.showError(j,b[m].message[1],s,r,f),h=!0):b[m].max&&!g&&a.enLength(l)>b[m].max?(this.showError(j,b[m].message[2],s,r,f),h=!0):(j?r.hide(function(){a(this).display()}):/radio|checkbox/.test(b[m].type)?f.parent().css("color","#333"):f.css("border-color","#DBD8D1"),g||k.push({name:b[m].name,title:b[m].title,value:l}))}h?"function"==typeof e&&e():(a.Log("form submit complete, failCallback is null",3),"function"==typeof c?c(k):a.Log("form submit complete, callback is null",3))},showError:function(b,
c,d,e,f){var g=this;b&&c?a.browser.mobile?(this.messageErrorToast&&(this.messageErrorToast.remove(),this.messageErrorToast=null,messageErrorTimeout&&clearTimeout(messageErrorTimeout)),b=10<c.length?300:250,this.messageErrorToast=new a.Toast('<div id="#message_error" style="position: relative;width: '+(b-50)+'px; height:30px; line-height: 30px;z-index:100; color: #FFF; top: 30px; left: 25px; text-align:center;font-weight:bold">'+c+"</div>",{width:b,height:90}),this.messageErrorTimeout=setTimeout(function(){g.messageErrorToast.remove();
g.messageErrorToast=null;f.get(0).focus()},2E3)):(d.html(c),e.display(1).show(),f.get(0).focus()):/radio|checkbox/.test(fields[i].type)?f.parent().css("color","#f00"):f.css("border-color","#f00").get(0).focus()}}});a.Transfer=a.Class.create();a.Transfer.prototype={name:"Transfer",button:null,element:null,form:null,iframe:null,proxy:null,options:null,debug:!0,fkey:"",initialize:function(b,c){this.button=c;var d=a.randomChar(16);this.options=a.extend({onError:new Function,onChange:new Function,callback:new Function,
name:d,curName:"",compSize:512E3,params:{},target:"iframe-transfer-"+d},b);if(this.options.server){this.proxy=a({tag:"IFRAME",name:"proxy-"+d,src:this.options.server.substring(0,this.options.server.lastIndexOf("/"))+"/proxy.html?t="+a.getTime(),style:a.STYLE_NBODY+"width:0px;height:0px;display:none;"}).appendTo(a(this.button)).get(0).contentWindow;var e=this,d=Math.max(20,this.button.width(),parseFloat(this.button.css("width"))),f=Math.max(20,this.button.height(),parseFloat(this.button.css("height"))),
d=a.STYLE_BODY+"width:"+d+"px;height:"+f+"px;overflow:hidden;";this.completed=function(a){/^(?:loaded|complete|undefined)$/.test(this.readyState)&&(e.iframe.removeEvent("readystatechange",e.completed).removeEvent("load",e.completed),e.transferComplete(a,e.fkey))};this.form=a({tag:"FORM",action:"",method:"POST",target:this.options.target,enctype:"multipart/form-data",style:d}).appendTo(this.button,!0);this.iframe=a({tag:"IFRAME",name:this.options.target,src:"about:blank",style:d+"width:0;height:0;display:none;"}).appendTo(this.button,
!0);this.element=a({tag:"INPUT",type:"file",name:this.options.name,accept:this.options.accept||"*",style:d,title:this.button.attr("title")||""}).appendTo(this.form,!0).css("opacity",0);this.element.click(function(){""!==this.value&&e.form.get(0).reset();e.iframe.bind("readystatechange",e.completed).bind("load",e.completed);e.fkey=a.randomChar(16)}).bind("change",function(a){var b={};this.files?(b.name=this.files[0].name,b.size=this.files[0].size):(b.name=this.value.substring(this.value.lastIndexOf("\\")+
1),b.size="");b.name&&(e.options.onChange(b),e.fileChange(a,this.files||this.value))})}else a.Log("server is null",3)},transferComplete:function(b,c){var d=this;c&&(this.debug&&a.Log("$.upload.transferComplete(event, "+c+")"),a.jsonp(this.options.server+"?"+a.toURI(a.extend({getaction:1,fkey:c},this.options.params))+"#rnd",function(b){d.debug&&a.Log("get transfer file info:"+a.JSON.toJSONString(b),1);b.name=d.options.curName||d.options.name||"";d.options.callback(b)}))},fileChange:function(b,c){var d=
this;this.isMobileCompTransf(c,function(e){e?a.browser.oldAndroid?a.require("jpeg_encoder_basic.js?siteid="+d.options.params.siteid,function(){d.mobileCompTransf(b,c)}):d.mobileCompTransf(b,c):d.commonTransf(b,c)})},isMobileCompTransf:function(b,c){if(a.browser.mobile&&(window.URL||window.webkitURL)&&document.createElement("canvas"))if(-1<b[0].name.toLowerCase().indexOf("jpg"))c(!0);else if(window.FileReader&&window.DataView){var d=new FileReader;d.onload=function(b){b=new DataView(b.target.result);
255==b.getUint8(0)&&216==b.getUint8(1)?c(!0):c(!1)};d.readAsArrayBuffer(b[0])}else c(!1);else c(!1)},commonTransf:function(b,c){var d="uploadfile"==this.options.params.action?!0:!1,e,f;try{e=d?this.proxy.fileOptions.fileMaxSize:this.proxy.fileOptions.imageMaxSize,f=d?this.proxy.fileOptions.fileExt:this.proxy.fileOptions.imageExt}catch(g){f=e=null}if("string"===typeof c)this.debug&&a.Log("Name: "+c,2);else for(var k,d=0;d<c.length;d++){var j=c[d];k=-1<j.name.indexOf(".")?j.name.match(/\.[^\.]+$/)[0].replace(".",
"").toLowerCase():"";if(this.options.maxSize&&j.size>this.options.maxSize||e&&j.size>e){this.options.onError({type:9,name:j.name,size:j.size,etype:"SIZE",maxSize:this.options.maxSize||e});return}if("*"!=this.options.accept&&this.options.accept||f){if(this.options.accept&&-1<this.options.accept.indexOf("/*")){if(k=RegExp(this.options.accept.replace(/\//,"\\/"),"gi"),!k.test(j.type)){a.Log("accept:"+this.options.accept+", type:"+j.type,2);this.options.onError({type:9,name:j.name,size:j.size,etype:"TYPE"});
return}}else{if(this.options.accept&&-1>=this.options.accept.indexOf(j.type)){a.Log("accept:"+this.options.accept+", type:"+j.type,2);this.options.onError({type:9,name:j.name,size:j.size,etype:"TYPE"});return}if(f&&-1<f.indexOf(k))continue;else if(f&&-1==f.indexOf(k)){this.options.onError({type:9,name:j.name,size:j.size,ext:f,etype:"TYPE"});return}}this.options.curName=j.name;this.debug&&a.Log("Name: "+this.options.curName)}}this.debug&&a.Log("$.upload.fileChange()");this.form.attr("action",this.options.server+
"?"+a.toURI(a.extend({fkey:this.fkey,rnd:a.getTime()},this.options.params)));a.browser.mobile&&this.options.callback({status:"startUpload",oldfile:c[0].name});this.form.get(0).submit()},mobileCompTransf:function(b,c){var d=this;this.options.callback({status:"startCompress",oldfile:c[0].name});new a.ImageOrientation(c[0],function(b,f){new a.CompressImg(c[0],{orientation:f},function(b,e){d.formData=new FormData;d.formData.append("base64",e);d.formData.append("fname",a.getTime()+".jpg");d.options.action=
"uploadimage";d.options.siteid=d.options.params.siteid;a.each(d.options,function(b,a){d.formData.append(b,a)});d.uploadCallBack=function(b){"success"==b.status?(b=b.event.target.responseText,d.options.callback(a.JSON.parseJSON(b))):"error"==b.status&&d.options.callback("error")};d.options.callback({status:"startUpload",oldfile:c[0].name,compress:!0});try{d.proxy.uploadFile(d.options.server,d.formData,d.uploadCallBack)}catch(f){a.Log("base64 upload"+f.message,3)}})})},base64Transf:function(b){var c=
this;this.fkey=a.getTime();new a.POST(this.options.server+"?action=uploadimage",a.extend({base64:b,fname:a.getTime()+".png",fkey:this.fkey,rnd:a.getTime()},this.options.params),function(b){c.transferComplete(b,c.fkey)})}};a.CompressImg=a.Class.create();a.CompressImg.prototype={ctx:null,canvas:null,url:null,image:null,blob:null,compBlob:null,dataurl:null,resize:{width:null,height:null},options:{width:null,height:null,quality:0.7},initialize:function(b,c,d){var e=this;this.url=window.URL||window.webkitURL;
this.canvas=document.createElement("canvas");this.blob="string"===typeof b?b:this.url.createObjectURL(b);this.options=a.extend(c,this.options);this.image=new Image;this.image.onerror=function(){a.Log("\u52a0\u8f7d\u56fe\u7247\u5931\u8d25\uff01")};this.image.onload=function(b){e.getCompImage();d(b,e.dataurl);for(var a in e)e.hasOwnProperty(a)&&(e[a]=null)};this.image.crossOrigin="*";this.image.src=e.blob},getCompImage:function(){this.ctx=this.canvas.getContext("2d");this.resize=this._getResize();this.canvas.width=
this.resize.width;this.canvas.height=this.resize.height;this.ctx.fillStyle="#fff";this.ctx.fillRect(0,0,this.canvas.width,this.canvas.height);switch(this.options.orientation){case 3:this.ctx.rotate(180*Math.PI/180);this.ctx.drawImage(this.image,-this.resize.width,-this.resize.height,this.resize.width,this.resize.height);break;case 6:this.ctx.rotate(90*Math.PI/180);this.ctx.drawImage(this.image,0,-this.resize.width,this.resize.height,this.resize.width);break;case 8:this.ctx.rotate(270*Math.PI/180);
this.ctx.drawImage(this.image,-this.resize.height,0,this.resize.height,this.resize.width);break;case 2:this.ctx.translate(resize.width,0);this.ctx.scale(-1,1);this.ctx.drawImage(this.image,0,0,this.resize.width,this.resize.height);break;case 4:this.ctx.translate(resize.width,0);this.ctx.scale(-1,1);this.ctx.rotate(180*Math.PI/180);this.ctx.drawImage(this.image,-this.resize.width,-this.resize.height,this.resize.width,this.resize.height);break;case 5:this.ctx.translate(resize.width,0);this.ctx.scale(-1,
1);this.ctx.rotate(90*Math.PI/180);this.ctx.drawImage(this.image,0,-this.resize.width,this.resize.height,this.resize.width);break;case 7:this.ctx.translate(resize.width,0);this.ctx.scale(-1,1);this.ctx.rotate(270*Math.PI/180);this.ctx.drawImage(this.image,-this.resize.height,0,this.resize.height,this.resize.width);break;default:this.ctx.drawImage(this.image,0,0,this.resize.width,this.resize.height)}if(a.browser.oldAndroid){var b=new JPEGEncoder,c=this.ctx.getImageData(0,0,this.canvas.width,this.canvas.height);
this.dataurl=b.encode(c,100*this.options.quality)}else this.dataurl=this.canvas.toDataURL("image/jpeg",this.options.quality);this.url.revokeObjectURL(this.blob)},_getResize:function(){var b=this.image,a=this.options.width,d=this.options.height,e={width:b.width,height:b.height};-1<"5678".indexOf(this.options.orientation)&&(e.width=b.height,e.height=b.width);b=e.width/e.height;a&&d?b>=a/d?e.width>a&&(e.width=a,e.height=Math.ceil(a/b)):e.height>d&&(e.height=d,e.width=Math.ceil(d*b)):a?a<e.width&&(e.width=
a,e.height=Math.ceil(a/b)):d&&d<e.height&&(e.width=Math.ceil(d*b),e.height=d);for(;3264<=e.width||2448<=e.height;)e.width*=0.8,e.height*=0.8;return e}};a.ImageOrientation=a.Class.create();a.ImageOrientation.prototype={initialize:function(b,c){if(!window.FileReader||!window.DataView)return 1;var d=this,e=new FileReader;e.onload=function(b){c(a.Event.fixEvent(b),d._readImageOrientation(b.target.result))};e.readAsArrayBuffer(b)},_readImageOrientation:function(b){var a=new DataView(b);if(255!=a.getUint8(0)||
216!=a.getUint8(1))return 1;for(var d=2,b=b.byteLength,e;d<b;){if(255!=a.getUint8(d))return 1;e=a.getUint8(d+1);if(225==e)return this._getOrientationFromExif(a,d+4,a.getUint16(d+2)-2);d+=2+a.getUint16(d+2)}},_getOrientationFromExif:function(b,a){if("Exif"!=this._getStringFromDB(b,a,4))return 1;var d,e=a+6;if(18761==b.getUint16(e))d=!1;else if(19789==b.getUint16(e))d=!0;else return 1;if(42!=b.getUint16(e+2,!d))return 1;var f=b.getUint32(e+4,!d);return 8>f?1:this._getOrientationFromTag(b,e,e+f,d)},
_getOrientationFromTag:function(b,a,d,e){var f=b.getUint16(d,!e),g,h,j;for(j=0;j<f;j++)if(g=d+12*j+2,h=b.getUint16(g,!e),274==h)return this._getOrientationValue(b,g,a,d,e);return 1},_getOrientationValue:function(a,c,d,e,f){var g=a.getUint16(c+2,!f),e=a.getUint32(c+4,!f),d=a.getUint32(c+8,!f)+d;switch(g){case 3:if(1==e)return a.getUint16(c+8,!f);c=2<e?d:c+8;d=[];for(g=0;g<e;g++)d[g]=a.getUint16(c+2*g,!f);return d}},_getStringFromDB:function(a,c,d){var e="";for(n=c;n<c+d;n++)e+=String.fromCharCode(a.getUint8(n));
return e}};a.DialogChat=new a.Class.create;a.DialogChat.prototype={contains:null,background:null,iframe:null,display:!1,selector:"",def:{close:!1,parent:window,margin:10,border:0,style:{height:"auto"},resizeFunc:null},options:null,_funcResize:new Function,initialize:function(b,c){var d=this;this.options=a.extend({},this.def,c);this.id=a.randomChar();this.selector=".dialog-container-"+this.id;this._create();this._style(this.options.style);this.display=!0;this.options.close&&(b+='<div class="dialog-button-close" style="'+
a.STYLE_NBODY+'font-size:14px;position:absolute;right:10px;top:10px;width:20px;height:20px;line-height:20px;text-align:center;cursor:pointer;">x</div>');this.container.html(b);setTimeout(function(){d.container.css({top:Math.max(0,(a(d.options.parent).height()-Math.max(d.container.height(),200))/2)+"px"})},5);this._funcResize=function(){d.resize()};this.options.parent==window&&a(window).addEvent("resize",this._funcResize);this.container.find(".dialog-button-close").click(function(){d.close()})},close:function(){var b=
this;this.options.parent==window&&a(window).removeEvent("resize",this._funcResize);a(this.selector).hide(function(){a(".dialog-iframe-"+b.id+",.dialog-background-"+b.id).remove();a(b.selector).remove();b.display=!1})},resize:function(b,c){b=b||a(this.options.parent).width();c=c||a(this.options.parent).height();a(".dialog-iframe-"+this.id+",.dialog-background-"+this.id).css({width:b+"px",height:c+"px"});var d="auto"===this.options.style.height?"auto":c-2*this.options.margin-2*this.options.border;this.container.css({width:b-
2*this.options.margin-2*this.options.border+"px",height:"auto"==d?"auto":d+"px","max-width":b+"px","max-height":c-40+"px"});this.container.css("top",Math.max(0,(c-Math.max("auto"==d?this.container.height():d,200))/2)+"px");this.options.resizeFunc&&this.options.resizeFunc.call()},_create:function(){var b=this.options.parent==window?document.body:this.options.parent,c=this.options.parent==window?"fixed":"absolute";this.iframe=a({tag:"IFRAME",className:"dialog-iframe-"+this.id,style:a.STYLE_NBODY+"position:"+
c+";display:none;left:0;top:0;margin:0;padding:0;border:0;width:100%;z-index:8888;"}).appendTo(b);this.background=a({tag:"div",className:"dialog-background-"+this.id,style:a.STYLE_NBODY+"position:"+c+";left:0;top:0;margin:0;padding:0;border:0;width:100%;background-color:#000;z-index:8888;"}).appendTo(b);this.container=a({tag:"div",className:"dialog-container-"+this.id,style:a.STYLE_BODY+"position:"+c+";left:0;top:0;margin:0;min-height:"+(this.options.minHeight?this.options.minHeight:200)+"px;border-radius:0px;z-index:"+
(a.browser.mobile?9E3:2147483647)+";background:#fff;overflow-x:hidden;overflow-y:auto;"}).appendTo(b)},_style:function(b){var c=a(this.options.parent).width(),d=a(this.options.parent).height();a(".dialog-iframe-"+this.id+",.dialog-background-"+this.id).css({width:c+"px",height:a(this.options.parent).height()+"px"});this.background.css({opacity:0.6});var e=(this.options.margin+"").split(" ");1==e.length&&e.push(this.options.margin);this.container.css(b).css({left:e[0]+"px",top:e[1]+"px",width:c-2*
e[0]-2*this.options.border+"px",height:"auto"===this.options.style.height?"auto":d-2*e[1]-2*this.options.border+"px"})}};a.Toast=new a.Class.create;a.Toast.prototype={id:null,container:null,toast:null,options:{},initialize:function(b,c){var d=this;this.id=a.randomChar();this.options=a.extend(this.options,c);this.toastOpacity=a({tag:"div",className:"toast-opacity-"+this.id,style:a.STYLE_BODY+"position:relative;z-index:9000;width:"+this.options.width+"px;height:"+this.options.height+"px;margin-left:"+
(a(window).width()-this.options.width)/2+"px;margin-top:"+(a(window).scrollTop()+(a(window).height()-this.options.height-100)/2)+"px;background-color:#000;opacity:0.5;border-radius:5px;font-size:16px;color:white;text-align:center;line-height:"+this.options.height+"px"});this.toast=a({tag:"div",className:"toast-"+this.id,style:a.STYLE_BODY+"position:relative;z-index:10000;width:"+this.options.width+"px;height:"+this.options.height+"px;margin-left:"+(a(window).width()-this.options.width)/2+"px;margin-top:"+
-this.options.height+"px;background-color:none;border-radius:5px;font-size:16px;color:white;text-align:center;line-height:"+this.options.height+"px"});this.toast.html(b);this._create();this._funcResize=function(){d.resize()};this._funRemove=function(){d.remove()};a(window).addEvent("resize",this._funcResize)},_create:function(){this.toastOpacity.appendTo(document.body);this.toast.appendTo(document.body)},change:function(b){a(".toast-"+this.id).html(b)},resize:function(){var b=a(window).width(),c=
a(window).height(),d=0<(b-this.options.width)/2?(b-this.options.width)/2:0,e=0<(c-this.options.height-100)/2?a(window).scrollTop()+(c-this.options.height-100)/2:a(window).scrollTop();a(".toast-opacity-"+this.id).css({"margin-left":d+"px","margin-top":e+"px","max-width":b+"px","max-height":c+"px"});a(".toast-"+this.id).css({"margin-left":d+"px","margin-top":-this.options.height+"px","max-width":b+"px","max-height":c+"px"})},remove:function(){a(".toast-opacity-"+this.id).remove();a(".toast-"+this.id).remove()}};
a.GifTimer=a.Class.create();a.GifTimer.prototype={id:null,inter:null,timeout:null,options:{inTimeFunc:null,outTimeFunc:null,doTime:null,allTime:null},initialize:function(b){var c=this;this.options=a.extend(this.options,b);this.inter=setInterval(function(){c.options.inTimeFunc.call(c)},this.options.doTime);this.timeout=setTimeout(function(){clearInterval(c.inter);c.options.outTimeFunc.call(c)},this.options.allTime)},remove:function(){a.Log("giftimer remove");clearInterval(this.inter);clearTimeout(this.timeout);
this.timeout=this.inter=null}};a.Music=a.Class.create();a.Music.prototype={msgid:null,url:null,type:null,duration:null,audioFlag:!0,musicEl:null,viewCallback:null,eventCallback:null,container:null,debugStr:"[nTalk Music]: ",initialize:function(a,c,d,e,f,g,h){this.msgid=a;this.url=c;this.type=d;this.duration=e;this.viewCallback=f;this.eventCallback=g;this.container=h;(this.audioFlag=this.canPlayAudioMP3())?this.createAudioPlayer():this.createSwfPlayer();this.viewCallback.call(this,"init");this.eventCallback.call(this,
"init")},createAudioPlayer:function(){var b=this;this.musicEl=document.createElement("audio");this.musicEl.src=this.url;this.musicEl.type=this.type;this.musicEl.stop=function(){this.pause();this.currentTime=0};a.Event.addEvent(this.musicEl,"ended",function(){a.Log(b.debugStr+" trigger ended stop mp3");b.viewCallback.call(b,"stop")});this.musicEl.getPaused=function(){return this.paused}},createSwfPlayer:function(){var b=this,c="ntalker_swf_mp3Player_container_"+this.msgid,d="ntalker_swf_mp3player_"+
this.msgid,e=a.flashHtml(d,a.sourceURI+"fs/music.swf","id="+d);this.musicEl=document.createElement("div");this.musicEl.innerHTML+=e;this.musicEl.id=c;this.container.append(this.musicEl.outerHTML);var f=a.browser.msie&&7>=a.browser.ieversion?window[d]:document[d];setTimeout(function(){f.emit("load",b.url);f.emit("stop");b.musicEl.play=function(){f.emit("play")};b.musicEl.stop=function(){f.emit("stop")};b.musicEl.getPaused=function(){return 0==f.getPaused()}},1E3)},emit:function(){this.musicEl.getPaused()?
this.play():this.stop()},play:function(){a.Log(this.debugStr+"play mp3");this.musicEl.play();this.viewCallback.call(this,"play")},stop:function(){a.Log(this.debugStr+"stop mp3");this.musicEl.stop();this.viewCallback.call(this,"stop")},canPlayAudioMP3:function(){try{var a=document.createElement("audio");return!(!a.canPlayType||!a.canPlayType("audio/mpeg;").replace(/no/,""))}catch(c){return!1}}};a.paste=a.Class.create();a.paste.prototype={data:null,callback:null,debugStr:"[nTalk pasteDate]: ",initialize:function(a,
c){this.data=a.clipboardData||window.clipboardData;this.callback=c},getImgBase64Str:function(){var b=this,c=this.data;if(!c)return null;if("function"==typeof webInfoChanged)this.callback(c.getData("image/x-vnd.adobe.air.bitmap").toDataURL());else if(a.browser.chrome||a.browser.opera){var d,e=c.items;if(e){d=e[0];for(var c=c.types||[],f=0,g=c.length;f<g;f++)if("Files"===c[f]){d=e[f];break}d&&"file"===d.kind&&d.type.match(/^image\//i)?(d=d.getAsFile(),e=new FileReader,e.onload=function(a){b.callback(a.target.result)},
e.readAsDataURL(d)):this.callback()}}else this.callback()}}}})(nTalk);

/* @file im.js
 * @date 2016.04.28 03:22:50 
 */
(function(a){a.im||(a.tipsicon=a.sourceURI+"images/tipsicon."+(a.browser.msie6?"gif":"png"),a.extend({CON_LCRM_FIX:"LCRM_",currentCount:0,im:{connect:null,time:3,args:null,options:null,tipElement:null,isInvite:!1,start:function(){var b=this;this.connect?a.Log("im connected",2):(this.options={siteid:a.global.siteid,settingid:a.global.settingid,surl:a.server.flashserver,r:a.baseURI,ref:a.referrer,fsid:a.global.trailid,cid:a.global.pcid,presenceserver:a.server.presenceserver,presencegoserver:a.server.presencegoserver,
t2dstatus:a.server.t2dstatus,crmcenter:a.server.crmcenter,coopserver:a.server.coopserver,loadnid:a.CON_LOAD_MODE_NID},a.user.id&&(this.options=a.merge(this.options,a.whereGet(a.user,["id","name"],["u","n"]))),a.require({comet:"nt2.js?siteid="+a.extParmas.siteid},function(c){c?(b.connect=new a.connectPresence(b.options,a.server.close_im_flash||"0",a.server.connect_type),a.IMPRESENCE=b.connect,a.promptwindow.callbackFocus=function(){b.onPageFocus()},a.promptwindow.callbackBlur=function(){b.onPageBlur()},
a.listenMouseOutEvent(),setInterval(function(){b.intervalVerify()},5E3),a.moveCheck=setInterval(function(){0==a.moveTime&&(1==a.currentCount&&a.moveCheckFlag)&&(a.moveCheckFlag=!1,setTimeout(function(){0==a.moveTime&&1==a.currentCount&&a.showBeforeLeavePlan();a.moveCheckFlag=!0},2E3))},1E3)):a.Log("Loaded $comet mode failed",3)}))},callReceiveSysMessage:function(b,c){var d,e,f;e=b.id||"";!b.settingid&&e&&(f=e.split("_").splice(0,2).join("_"),b.settingid=-1<a.global.settingid.indexOf(f)||f.indexOf("kf_")?
a.global.settingid:f+"_9999");switch(b.calltype){case 10:a.browser.mobile&&a.global.pageinchat?a.isFunction(im_receiveMessage)&&im_receiveMessage(b.settingid,c):a.chatManage&&(d=a.chatManage.get(b.settingid,e))?(d.reconnect(null,e,-1),a.chatManage.callReceive(d.settingid)):3==a.server.isnoim?a.im_openInPageChat(b.settingid,"",e,{single:-1,autoconnect:!0},""):a.im.showTips(b,c);break;case 1:case 2:a.base.startLCrm(b.content);break;default:b.autoOpen||3==a.server.isnoim?(a.im&&a.im.refuseInvite(e,b.inviteid,
0),a.chatManage&&(d=a.chatManage.get(b.settingid,e))?(d.reconnect(null,e,-1),a.chatManage.callReceive(d.settingid)):a.im_openInPageChat&&a.im_openInPageChat(b.settingid,"",e,{single:-1,autoconnect:1},"")):this.showTips(b,c,!0)}},onPageFocus:function(){a.IMPRESENCE.setPageFocus(!0,a.title,a.url,0);this.intervalVerify()},onPageBlur:function(){a.IMPRESENCE.setPageFocus(!1)},intervalVerify:function(){var b,c;b=a.loadLCrm();a.each(b,function(b,e){1!=e.trigger&&a.im.connect.currentPage.get()&&(c=a.extend(e,
{cw:a.currentCount}),a.base.startLCrm(c,!1,!0),a.flashData.remove(a.CON_LCRM_FIX+c.token))})},showTips:function(b,c,d){this.settingid=b.settingid||a.global.settingid||"";this.destid=b.id||"";this.sessionid=b.sid||"";this.inviteid=b.inviteid||"";this.isInvite=d;b=this.destid.split("_ISME9754_T2D_");this.sellerid=-1<b[0].indexOf("kf_")||b[0]==a.global.siteid?"":b[0];a.require(a.tipsicon,function(b){b.error&&a.Log("cache chat icon failure",3)});this._createTips();this.tipElement.find(".ntalk-tips-body").html(c);
this.tipElement.find(".ntalk-tips-button").html("\u7acb\u523b\u54a8\u8be2");a.promptwindow.startPrompt("",a.lang.news_new,!0)},hideTips:function(){var b=this;this.tipElement&&this.tipElement.length&&this.tipElement.hide(500,function(){a(this).remove();b.tipElement=null})},openChat:function(){this.hideTips();a.browser.mobile||!a.global.pageinchat?a.im_openOutPageChat(this.settingid,"",this.destid,{manual:1},"",this.sellerid):a.im_openInPageChat(this.settingid,"",this.destid,{single:-1,autoconnect:this.isInvite?
-1:1,manual:1},"")},_createTips:function(){var b=this;if(!this.tipElement||!this.tipElement.length){var c=['<div class="ntalk-tips-background" style="margin:0;padding:10px;border:0;background:url(',a.tipsicon,') no-repeat 0 0;color:#333333;font:normal 12px/160% Arial,SimSun;text-align:left;height:150px;width:205px;"><div class="ntalk-tips-body" style="margin:0;padding:0;border:0;float:left;font:normal 12px/160% Arial,SimSun;color:#333;height:60px;overflow:hidden;text-align:left;white-space:normal;width:156px;word-break:break-all;"></div><div class="ntalk-tips-close" style="background:url(',
a.tipsicon,') no-repeat -7px -120px;margin:5px;padding:0;border:0;cursor:pointer;font:normal 1px/1px Arial;height:20px;left:166px;position:absolute;top:0px;width:20px;"></div><div class="ntalk-tips-button" style="background:#008CD4;margin:0;padding:0;border:0;color:#FFFFFF;cursor:pointer;height:24px;left:105px;font:normal 12px/24px Arial,SimSun;position:absolute;text-align:center;top:78px;width:69px;"></div></div>'].join("");this.tipElement=a({className:"ntalk-tips-container",style:"margin:0;padding:0;border:none;float:none;font:normal normal normal 12px/160% Arial,SimSun;width:206px;height:112px;z-index:99999;"}).appendTo(!0).fixed({right:0,
bottom:0}).html(c);this.tipElement.click(function(c){a.Event.fixEvent(c).stopPropagation();b.openChat()});this.tipElement.find(".ntalk-tips-button").click(function(c){a.Event.fixEvent(c).stopPropagation();b.openChat()}).hover(function(){a(this).css("background","#007AB9")},function(){a(this).css("background","#008CD4")});this.tipElement.find(".ntalk-tips-close").click(function(c){a.Event.fixEvent(c).stopPropagation();b.hideTips()}).hover(function(){a(this).css("background-position","-27px -120px")},
function(){a(this).css("background-position","-7px -120px")})}},refuseInvite:function(b,c,d){a.server.presencegoserver?!b||!c?a.Log("auto invite",1):a.require(a.server.presencegoserver+"?"+a.toURI({action:"",query:"invtrst",suid:a.user.id,duid:b,rst:d,invid:c,tk:a.global.userToken})+"#rnd"):a.Log("presencegoserver is null",2)}}}),a.extend({listenMouseEvent:!1,lcrmGoAwayClientY:0,lcrmGoAwayView:!1,moveTime:0,moveCheck:null,moveCheckFlag:!0,loadLCrm:function(){var b=a.flashData.get(),c={},d;for(d in b)"function"!=
typeof b[d]&&b[d]&&-1<d.indexOf(a.CON_LCRM_FIX)&&(c[d]=b[d]);return c},listenMouseOutEvent:function(b){var c=this,d=function(b){b=a.Event.fixEvent(b);(b.relatedTarget||b.toElement)&&!c.lcrmGoAwayView&&c.setMouseOutWindow(b,!1)},e=function(b){b=a.Event.fixEvent(b);!b.relatedTarget&&!b.toElement&&(c.setMouseOutWindow(b,!0),c.moveTime=0)},f=function(b){b=a.Event.fixEvent(b);c.setMouseOutWindow(b,"mousemove");null!=a.moveCheck&&(a.moveCheck=null);c.moveTime=a.getTime()};!this.listenMouseEvent&&!a.browser.mobile&&
(this.listenMouseEvent=!0,!0===b?(a(document).removeEvent("mouseover",d),a(document).removeEvent("mouseout",e),a(document).removeEvent("mousemove",f)):(a(document).addEvent("mouseover",d),a(document).addEvent("mouseout",e),a(document).addEvent("mousemove",f)))},setMouseOutWindow:function(b,c){"mousemove"===c?this.lcrmGoAwayClientY=0<b.clientY?b.clientY:this.lcrmGoAwayClientY:(this.lcrmGoAwayView=c,0>b.clientY&&50>this.lcrmGoAwayClientY&&1==a.currentCount&&setTimeout(function(){0==a.moveTime&&a.showBeforeLeavePlan()},
500))},_getExistPageList:function(){try{return a.store.get("IM_EXIST_PAGEARR").split(",")}catch(b){return[]}},showBeforeLeavePlan:function(){var b,c;b=a.loadLCrm();a.each(b,function(b,e){0!=e.trigger&&(c=a.extend(e,{trigger:0,cw:a.currentCount}),a.base.startLCrm(c,!1,!0),a.flashData.remove(a.CON_LCRM_FIX+c.token))})}}),a.extend({fIM_onPresenceReceiveSysMessage:function(b,c){a.Log('$.fIM_onPresenceReceiveSysMessage("'+b+'", "'+a.JSON.toJSONString(c)+'")',1);setTimeout(function(){var b,e,f;e=a.clearHtml(c.substr(0,
c.indexOf("ntalker://")));f=c.substr(c.indexOf("ntalker://")+10);try{b=a.JSON.parseJSON(f)}catch(h){a.Log("nTalk.fIM_onPresenceReceiveSysMessage():"+h.message,3);return}a.im.callReceiveSysMessage(b,e)},0);return!0},fIM_onGetFlashServer:function(){return!0},connectStatus:-1,fIM_updateUserStatus:function(b,c){setTimeout(function(){a.Log("$.fIM_updateUserStatus("+b+', "'+c+'")');a.connectStatus=b;if(2==a.connectStatus)try{a.IMPRESENCE.setPageFocus(!0,a.title,a.url,1)}catch(d){a.Log(d,3)}},0);return!0},
fIM_presenceSetIMSid:function(b){a.Log("fIM_presenceSetIMSid(userToken:"+b+")",1);a.global.userToken=b;return!0},fIM_presenceSetMyClientID:function(b){a.url_presenceFlashGoUrl=b;return!0},flashData:{debug:!1,reNumber:0,sessionData:null,checkFlash:function(b){!a.IMPRESENCE||!a.isFunction(a.IMPRESENCE.setJSData)?3<this.reNumber||(this.reNumber++,setTimeout(b,500)):b.call(this)},add:function(b,c){c&&(c=this.filter(a.JSON.toJSONString(c),!0));this.debug&&a.Log("$.flashData.add(k:"+b+", v:"+c+")",1);this.checkFlash(function(){try{return a.IMPRESENCE.setJSData(a.global.trailid,
b,c),!0}catch(d){return!1}})},remove:function(a){this.add(a,null,!1)},clearAll:function(){this.checkFlash(function(){try{return NTKF.IMPRESENCE.setJSData("","",""),!0}catch(a){return!1}})},get:function(b){var c,d={};if(!a.IMPRESENCE||!a.IMPRESENCE.getJSData)return d;c=a.IMPRESENCE.getJSData(a.global.trailid,b||"");try{c=a.JSON.parseJSON(c)}catch(e){}if("string"==typeof c)d=a.JSON.parseJSON(this.filter(c,!1)||"{}");else for(b in c)if(!a.isFunction(c[b]))try{d[b]=a.JSON.parseJSON(this.filter(c[b],!1))}catch(f){}return d},
filter:function(a,c){return!0===c?a.replace(/\"/gi,"{sy}"):a.replace(/\{sy\}/gi,'"')}}}),a.connectPresence=a.Class.create(),a.connectPresence.prototype={name:"connectPresence",options:null,manage:null,debug:!1,data:null,switchTimeId:null,_connected:!1,currentConnectType:"",initialize:function(b,c,d){var e;this.data=a.store;this.options=a.extend({nullparam:"",usemqtt:0},b);switch(d){case "mqtt":this.options.usemqtt=1;e="WebSocket"in window||"MozWebSocket"in window?"websock":"1"==c?"comet":"fssock";
break;case "rtmp":"1"==c?e="comet":a.flash.support&&(e="rtmp")}switch(e){case "websock":this.connect=this._createMqttConnect(this.options);break;case "fssock":case "rtmp":this.connect=this._createFlashConnect(this.options);break;default:this.options.usemqtt=0,this.connect=this._createCometConnect(this.options)}a.Log("new $.connectPresence(); conType: "+e+", isnoim:"+a.server.isnoim);this.manage=this.connect.manage?this.connect.manage:new a.pageManage;this.manage.options.onChanage=function(b){a.currentCount=
b;a.Log("page manage callback: current open window number:"+a.currentCount,1)};a.currentCount=this.manage.count;this.identid=this.manage.identid;this.connect.currentPage?this.currentPage=this.connect.currentPage:(a.Log("new $.CurrentPage("+this.identid+")",1),this.currentPage=new a.CurrentPage(this.identid,this.manage))},switchConnect:function(){this.stopSwitchConnect();this.currentConnectType!=a.CON_CONNECT_COMET?(a.Log("Flash abnormalities, switch the connection type. this.currentConnectType:"+
this.currentConnectType+" > comet",2),this.connect&&a.isFunction(this.connect.remove)&&a.flash.remove(this.connect),this.connect&&a.isFunction(this.connect.disconnect)&&this.connect.disconnect()):a.Log("Flash abnormalities",2)},stopSwitchConnect:function(){clearTimeout(this.switchTimeId);this.switchTimeId=null},setPageFocus:function(a,c,d){a&&this.currentPage.set(c,d)},closePresence:function(){if(this.connect)try{this.connect.closePresence()}catch(b){}this.currentConnectType==a.CON_CONNECT_FLASH&&
a.flash.remove(this.connect);this.manage=this.connect=null},setJSData:function(a,c,d){if(!a||""===a){var a=this.data.getAll(),e;for(e in a)"function"!=typeof a[e]&&-1<e.indexOf("JDATA_")&&this.data.remove(e)}else this.data.set("JDATA_"+a+"-"+c,d)},getJSData:function(){var b,c={};b=this.data.getAll();for(var d in b)"function"!=typeof b[d]&&-1<d.indexOf("JDATA_")&&(c[d]=b[d]);return a.JSON.toJSONString(c)},_createFlashConnect:function(b){a.Log("$.connectPresence._createFlashConnect()",1);var c=a("#nTalk-flash-element"),
b=a.flashHtml("ntkf_flash_impresence",a.sourceURI+"fs/impresence.swf?"+a.version.im,b);this.currentConnectType=a.CON_CONNECT_FLASH;c.length||(c=a(document.body).insert('<div id="nTalk-flash-element" class="nTalk-hidden-element" style="position: absolute; z-index: 9996; top: -200px;"></div>'));c.insert(b);a.browser.msie&&c.find("#ntkf_flash_impresence").display(1);return c.find("#ntkf_flash_impresence").get(0)},_createCometConnect:function(b){a.Log("$.connectPresence._createCometConnect()",1);this.currentConnectType=
a.CON_CONNECT_COMET;return new a.IMPresence(b)},_createMqttConnect:function(b){a.Log("$.connectPresence._createMqttConnect()",1);this.currentConnectType=a.CON_CONNECT_COMET;return new a.IMPresence(b)}},a.IMPresence=a.Class.create(),a.IMPresence.prototype={name:"IMPresence",options:null,connectParams:"userid username token sessionid nullparam nullparam nullparam siteid nullparam nullparam connectType pcid nullparam".split(" "),connect:null,debug:!1,login:!1,currentPage:null,_reCount:0,_waitTime:500,
_currentConnected:!1,_waitReconnectTimeID:null,_mqttFlag:!0,initialize:function(b){var c=this;this._wsFlag=1==b.usemqtt?!0:!1;this.options=a.extend({nullparam:""},a.whereGet(b,"siteid settingid cid surl u n s r ref fsid".split(" "),"siteid settingid pcid serverurl userid username sessionid resourceurl referrer flashsessionid".split(" ")));this.data=a.store;this._reCount=0;if(!this.options.pcid||10>=this.options.pcid.length)if(this.options.pcid=this.data.get("machineid"),!this.options.pcid||10>=this.options.pcid.length)this.options.pcid=
a.base._createScriptPCID();try{this.data.set("machineid",this.options.pcid)}catch(d){a.Log(d,3)}this.options.userid||(this.options.userid=a.base.userIdFix+this.options.pcid.substr(0,21));this._callback("fIM_presenceFlashReady",[this.options.userid,this.options.pcid]);this.manage=new a.pageManage({onInterval:function(a,b){c._onInterval.call(c,a,b)},onChanage:function(a,b){c._onChanage.call(c,a,b)}});this.identid=this.manage.identid;this.currentPage=new a.CurrentPage(this.identid,this.manage);this.setPageFocus(!0,
a.title,a.url)},loginConnect:function(){var b=this,c="",d=this._toArray(this.options,this.connectParams);this.debug&&a.Log("im.loginConnect()");this._callback("fIM_updateUserStatus",[1,""]);if(a.server.presenceserver){for(var e=a.server.presenceserver.split(";"),f=0;f<e.length;f++)-1<e[f].indexOf("ws://")&&(c=e[f]);c||(this._wsFlag=!1);this._wsFlag?this.connect=new a.mqttws({url:c,siteid:b.options.siteid,pcid:b.options.pcid,onCallback:function(){b._onCallback.apply(b,arguments)},loginMsg:a.JSON.toJSONString({method:"roomConnect",
params:d})}):(this.connect=new a.comet(a.server.presencegoserver,{timeout:20,onCallback:function(){b._onCallback.apply(b,arguments)},onComplete:function(a){b._onComplete.apply(b,arguments)},onAbnormal:function(a){b._onAbnormal.apply(b,arguments)},onTimeout:function(a){b._onTimeout.apply(b,arguments)}}),this.connect.connect({action:"conn",params:d.join(",")},"callback"))}},kaliveConnect:function(){this.debug&&a.Log("$.IMPresence.kaliveConnect()",1);var b=this;if(this._wsFlag){var c={method:"remoteKeepAlive",
params:[null,this.options.userid,this.options.clientid]};this.connect.kalive(a.JSON.toJSONString(c))}else c={action:"kalive",params:this._toArray(this.options,this.connectParams).join(","),clientid:this.options.clientid,machineid:this.options.pcid,token:this.options.token,uid:this.options.userid},setTimeout(function(){b.connect.kalive(c,"callback")},1E3)},reconnect:function(){var b=this;this._waitTime=3>=++this._reCount?500:1E3*+"034567890".charAt(Math.ceil(5*Math.random()));this.debug&&a.Log("$.IMPresence.reconnect() wait:"+
this._waitTime,1);this._waitReconnectTimeID=setTimeout(function(){b.connect.reconnect()},this._waitTime)},disconnect:function(){var a=this.data.getAll(),c;for(c in a)"function"!=typeof a[c]&&-1<c.indexOf("JDATA_")&&this.data.remove(c);clearTimeout(this._waitReconnectTimeID);this._waitReconnectTimeID=null},LoginResult:function(a,c,d,e){this.login=a;this.options.clientid=d;this.options.token=e;this._callback("fIM_updateUserStatus",[this.login?2:0,""]);this._callback("fIM_presenceSetIMSid",[this.login?
this.options.token:""]);this.login?this.kaliveConnect("call kalive"):this.reconnect("login relogin")},remoteNotifyChatWithGroup:function(b,c,d,e,f,h,g){if(g){b=a.clearHtml(g.substr(0,g.indexOf("ntalker://")));g=g.substr(g.indexOf("ntalker://")+10);try{a.JSON.parseJSON(g)}catch(i){}a.store.isStorageSupported?this._sendMessage2CurrenPage(b+"ntalker://"+g):this._callback("fIM_onPresenceReceiveSysMessage",[1,b+"ntalker://"+g])}else this.debug&&a.Log("message content is null",3)},remoteNotifyUserCode:function(){a.Log("do remoteNotifyUserCode!!!")},
remoteConfirmAddFriend:function(){a.Log("do remoteConfirmAddFriend")},_handleResponse:function(b,c){this[b]?this[b].apply(this,c):a.Log("The object of the method '"+b+"' does not exist",3)},_callback:function(b,c){if(a.hasOwnProperty(b))try{a[b].apply(this,c)}catch(d){}else a.Log("nTalk."+b+"(...)",2)},_onCallback:function(b,c){var d;this.debug&&a.Log("$.IMPresence.onCallback(  )");c.length&&(d=c[0],/LoginResult|LoginReslut/gi.test(d)?b&&this.LoginResult.apply(this,c.slice(1)):(this._handleResponse.call(this,
d,c.slice(1)),b&&this.kaliveConnect("call kalive")))},_onComplete:function(){var b=Array.prototype.slice.call(arguments);this.debug&&a.Log("$.IMPresence.onComplete( "+b[0]+","+b[1]+","+b[2]+" )");"kalive"==b[0]?this.kaliveConnect("complete kalive"):"login"==b[0]&&this.reconnect("abnormal login")},_onAbnormal:function(){var b=Array.prototype.slice.call(arguments);this.debug&&a.Log("$.IMPresence.onAbnormal( "+b[0]+","+b[1]+","+b[2]+" )",3);"login"==b[0]?this.reconnect("abnormal login"):this.kaliveConnect("abnormal kalive")},
_onTimeout:function(){var b=Array.prototype.slice.call(arguments);this.debug&&a.Log("$.IMPresence.onTimeout( "+b[0]+","+b[1]+","+b[2]+" )",3);"login"==b[0]?this.reconnect("time login"):this.kaliveConnect("timeout kalive")},_onInterval:function(b,c){this.currentConn=this.data.get("IM_CUREENT_CONNECT")||{identid:"",time:0};if(this.currentConn.identid&&this.currentConn.identid===this.identid)this.currentConn.time=a.getTime(),this.data.set("IM_CUREENT_CONNECT",this.currentConn),this._fireEvent("update");
else{var d;if(a.isArray(c))for(var e=0;e<c.length;e++)if((page=c[e])&&page[this.currentConn.identid])this._currentConnected=d=!0;this.currentConn.identid&&(this.currentConn.identid!==this.identid&&!d)&&(this.currentConn.identid="",this._currentConnected=!1,this._fireEvent("clear"));this.debug&&a.Log("currentConnect>>_onInterval:"+a.JSON.toJSONString(this.currentConn)+", _currentConnected:"+this._currentConnected);if((!this.currentConn.identid||""==this.currentConn.identid)&&!this._currentConnected){this.currentConn=
{identid:this.identid,time:a.getTime()};this._currentConnected=!0;try{this.data.set("IM_CUREENT_CONNECT",this.currentConn)}catch(f){a.Log(f,3)}this._fireEvent("add");this.loginConnect()}else this._fireEvent("wait")}},_onChanage:function(a){this.pageCount=a},_fireEvent:function(b){1==this.temp||!this.temp?(this.temp=1,this.debug&&"wait"!==b&&a.Log(this.identid+", "+b+" long connect, curPage:"+this.currentPage.get(),2)):5<=this.temp&&(this.temp=0);this.temp++;this._currentGetMessage()},_toArray:function(a,
c){var d=[];if(!a)return"error";for(var e=0;e<c.length;e++)d.push(a[c[e]]||"");return d},_sendMessage2CurrenPage:function(b){var c=this.data.get("IM_SEND_CURRENT_PAGE_DATA");b&&(this.Queue||(this.Queue=new a.Queue),c?this.Queue.enQueue({data:b}):this.data.set("IM_SEND_CURRENT_PAGE_DATA",b))},_currentGetMessage:function(){var b=this.data.get("IM_SEND_CURRENT_PAGE_DATA");if(b){try{b=a.JSON.parseJSON(b)}catch(c){}this.currentPage.get()&&b&&(this.data.remove("IM_SEND_CURRENT_PAGE_DATA"),this._callback("fIM_onPresenceReceiveSysMessage",
[1,b]),this.Queue&&(b=this.Queue.deQueue())&&this._sendMessage2CurrenPage(b.data))}},setPageFocus:function(a,c,d){!0===a&&this.currentPage.set(c,d)},closePresence:function(){if(this._wsFlag)this.connect.disconnect();else try{this.cometd.disconnect(!0)}catch(a){}this.data.remove("IM_CUREENT_CONNECT")},setJSData:function(a,c,d){if(!a||""===a){var a=this.data.getAll(),e;for(e in a)"function"!=typeof a[e]&&-1<e.indexOf("JDATA_")&&this.data.remove(e)}else this.data.set("JDATA_"+a+"-"+c,d)},getJSData:function(){var b,
c={};if((b=Array.prototype.slice.call(arguments,0,2).slice(0,2).join("-"))&&arguments[1])return a.JSON.toJSONString(this.data.get(b));b=this.data.getAll();for(var d in b)"function"!=typeof b[d]&&-1<d.indexOf("JDATA_")&&(c[d]=b[d]);return a.JSON.toJSONString(c)}},a.CurrentPage=a.Class.create(),a.CurrentPage.prototype={name:"CurrentPage",cachePageData:null,identid:"",debug:!1,manage:null,initialize:function(b,c){b?(this.identid=b,this.manage=c,this.data=a.store):a.Log("$.CurrentPage params failed",
3)},set:function(b,c){if(!b||!c)return a.Log("title is null, url is null"),!1;this.cachePageData={identid:this.identid,title:b,url:c};this.debug&&a.Log("$.CurrentPage.set():"+a.JSON.toJSONString(this.cachePageData),1);this.data.set("IM_CURRENT_PAGE",this.cachePageData)},get:function(){var b,c=!1;this.cachePageData=this.data.get("IM_CURRENT_PAGE");if(!this.cachePageData||a.isEmptyObject(this.cachePageData))return!1;var d=a._getExistPageList();if(0<d.length){for(var e=0;e<d.length;e++)if(b=d[e],b==
this.cachePageData.identid){c=!0;break}if(!1===c&&this.identid==d[d.length-1])return this.set(a.title,a.url),!0}this.debug&&(a.Log("::"+a.JSON.toJSONString(this.cachePageData)),a.Log("cache page identid:"+this.cachePageData.identid+", identid:"+this.identid+", currentPage: "+(this.cachePageData.identid==this.identid)));try{return this.cachePageData.identid==this.identid?!0:!1}catch(f){return!1}}})})(nTalk);
